import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import EventFilter from '../../components/events/EventFilter';
import EventList from '../../components/events/EventList';
import { getAllEvents } from '../../dummy-data';

export default function Events({ events }) {
	const [filteredEvents, setFilteredEvents] = useState('');
	const router = useRouter();

	// If month or year form is submitted, navigate programmatically
	function onFormSubmit(month, year) {
		const searchPath = `/events/${year}/${month}`;
		router.push(searchPath);
	}

	return (
		<div>
			<Head>
				<title>All Events</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>All events</h1>

				<EventFilter
					filteredEvents={filteredEvents}
					setFilteredEvents={setFilteredEvents}
					onFormSubmit={onFormSubmit}
				/>
				<p>{filteredEvents}</p>

				<EventList
					items={events}
					filteredEvents={filteredEvents.toLowerCase()}
				/>
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const allEventsQuery = `https://next-events-62c2a-default-rtdb.europe-west1.firebasedatabase.app/Events.json`;

	const response = await fetch(allEventsQuery);
	const data = await response.json();

	return {
		props: {
			events: data,
		},
		revalidate: 300,
	};
}
