import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { getFeaturedEvents } from '../dummy-data';
import EventList from '../components/events/EventList';
import { useState } from 'react';
import NewsletterSignUp from '../components/NewsletterSignUp';

export default function Home({ featuredEvents }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>NextJs Events</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<NewsletterSignUp />
				<h1>Homepage</h1>
				<EventList items={featuredEvents} />
			</main>
		</div>
	);
}

export async function getStaticProps() {
	// The filtering for featuredEvents is done in the query directly
	const featuredEventsQuery =
		'https://next-events-62c2a-default-rtdb.europe-west1.firebasedatabase.app/Events.json?orderBy="isFeatured"&equalTo=true';

	const response = await fetch(featuredEventsQuery);
	const data = await response.json();

	const events = [];

	// Firebase returns data as an Object, spread into an Array
	//TODO: This is repeated, extract to a utils file?
	for (const key in data) {
		events.push({
			id: key,
			...data[key],
		});
	}

	return {
		props: {
			featuredEvents: events,
		},
		revalidate: 1800,
	};
}
